#!/bin/bash
#
# Nagios check_docker plugin by George Jones IV
# This plugin will get the current state of the Docker service
#
# Prerequisites:
#
# usage: check_container 

dockerstatus=$( systemctl is-active docker )
cond1="active"
cond2="inactive"
cond3="unknown"

if [ "$dockerstatus" = "$cond1" ]; then
        echo "OK - $dockerstatus"
        exit 0
elif [ "$dockerstatus" = "$cond2" ]; then
        echo "CRITICAL - $dockerstatus"
        exit 2
elif [ "$dockerstatus" = "$cond3" ]; then
        echo "UNKNOWN - $dockerstatus"
        exit 3
fi
